// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(4025443179).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(3557321497);
}

export function ExportCAPEM(): $CancellablePromise<string> {
    return $Call.ByID(92948392);
}

/**
 * GetCloseAction returns the persisted close-behaviour preference
 * ("" = ask, "quit", "tray"). Unbound errors from config.json are swallowed
 * — a missing or malformed config just maps to "ask the user".
 */
export function GetCloseAction(): $CancellablePromise<string> {
    return $Call.ByID(2118618486);
}

export function GetCursorSettingsStatus(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(93837633).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(645976517).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUsageStats returns the aggregate token-use snapshot the Stats tab in the
 * Wails UI renders. Computed on demand from disk; safe to call any time
 * (even while the proxy is stopped — history persists across restarts).
 */
export function GetUsageStats(): $CancellablePromise<$models.UsageStats> {
    return $Call.ByID(1732265946).then(($result: any) => {
        return $$createType2($result);
    });
}

export function InstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2336299263).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.UserConfig> {
    return $Call.ByID(954104777).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenSettingsFolder(): $CancellablePromise<void> {
    return $Call.ByID(1122135673);
}

/**
 * RequestHide triggers the registered hide-to-tray callback. Called from
 * the frontend close dialog's "Minimize to tray" button.
 */
export function RequestHide(): $CancellablePromise<void> {
    return $Call.ByID(1630742069);
}

/**
 * RequestQuit triggers the registered quit callback. Called from the
 * frontend close dialog's "Quit" button. Runs the callback on its own
 * goroutine so the Wails RPC returns before the app actually tears down.
 */
export function RequestQuit(): $CancellablePromise<void> {
    return $Call.ByID(1739891086);
}

export function RevertCursorTweaks(): $CancellablePromise<$models.CursorSettingsStatus> {
    return $Call.ByID(1654344741).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveUserConfig(cfg: $models.UserConfig): $CancellablePromise<void> {
    return $Call.ByID(3337069704, cfg);
}

export function SetBaseURL(url: string): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(3745889402, url).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetCloseAction persists the user's choice from the close dialog. "quit"
 * and "tray" are the only meaningful values; anything else is normalised
 * to "" (which makes the dialog reappear on the next close — a safe reset).
 */
export function SetCloseAction(action: string): $CancellablePromise<void> {
    return $Call.ByID(1277049754, action);
}

/**
 * SetHideCallback registers the function main.go uses to hide the main
 * window to the system tray (keeping the proxy and tray icon alive).
 */
export function SetHideCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(1124718839, cb);
}

/**
 * SetQuitCallback registers the function main.go uses to fully tear the
 * app down (Stop proxy, remove tray icon, quit the Wails application).
 * Invoked from RequestQuit so the frontend close dialog can exit cleanly.
 */
export function SetQuitCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(3294985300, cb);
}

export function SetStateCallback(cb: any): $CancellablePromise<void> {
    return $Call.ByID(807242594, cb);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(764443870);
}

export function StartProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1886323464).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopProxy(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(1074329452).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestAdapter(index: number): $CancellablePromise<$models.ModelAdapterConfig> {
    return $Call.ByID(4077231351, index).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UninstallCA(): $CancellablePromise<$models.ProxyState> {
    return $Call.ByID(2155598834).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CursorSettingsStatus.createFrom;
const $$createType1 = $models.ProxyState.createFrom;
const $$createType2 = $models.UsageStats.createFrom;
const $$createType3 = $models.UserConfig.createFrom;
const $$createType4 = $models.ModelAdapterConfig.createFrom;
